const categories: Category[] = [
  {
    id: 'game-ui',
    title: '游戏UI设计',
    icon: <Layers className="w-8 h-8" />,
    description: '专注于游戏界面设计，打造沉浸式用户体验。从概念设计到最终实现，每一个像素都经过精心打磨，确保视觉与功能的完美融合。',
    tools: ['Figma', 'Photoshop', 'After Effects', 'Unity'],
    images: [
      { src: '/image/works/youxi/000.webp', alt: '游戏场景' },
      { src: '/image/works/youxi/001.webp', alt: '游戏场景' },
      { src: '/image/works/youxi/002.webp', alt: '游戏元素' },
      { src: '/image/works/youxi/003.webp', alt: '界面设计' },
      { src: '/image/works/youxi/004.webp', alt: '界面设计' },
      { src: '/image/works/youxi/005.webp', alt: '界面设计' },
      { src: '/image/works/youxi/006.webp', alt: '界面设计' },
      { src: '/image/works/youxi/007.webp', alt: '界面设计' },
      { src: '/image/works/youxi/008.webp', alt: '界面设计' },
      { src: '/image/works/youxi/009.webp', alt: '界面设计' },
      { src: '/image/works/youxi/010.webp', alt: '界面设计' },
    ],
  },
  {
    id: 'painting',
    title: '绘画',
    icon: <PenTool className="w-8 h-8" />,
    description: '数字绘画与插画创作，融合传统技法与现代数字工具，创造富有表现力的视觉作品。',
    tools: ['Procreate', 'Photoshop', 'Clip Studio Paint', 'Wacom'],
    images: [
      { src: '/image/works/huihua.webp', alt: '数字绘画作品' },
      { src: '/image/works/huihua/002.webp' },
      { src: '/image/works/huihua/003.webp', alt: '概念艺术' },
      { src: '/image/works/huihua/004.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/005.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/006.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/008.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/009.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/010.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/014.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/015.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/016.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/017.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/018.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/019.webp', alt: '传统绘画' },
      { src: '/image/works/huihua/020.webp', alt: '传统绘画' },
      { src: '/011.webp', alt: '传统绘画' },
      { src: '/012.webp', alt: '传统绘画' },
      { src: '/013.webp', alt: '传统绘画' },
    ],
  },
  {
    id: '3d-design',
    title: '3D设计',
    subtitle: '建模 · 材质贴图 · 渲染 · 三维动画',
    icon: <Box className="w-8 h-8" />,
    description: '三维建模、材质贴图、渲染及动画制作。从角色到场景，从产品到建筑，全方位的3D视觉解决方案。',
    tools: ['Blender', 'Cinema 4D', 'Substance Painter', 'ZBrush', 'Unreal Engine'],
    images: [
      { src: '/image/works/3d.webp', alt: '3D角色建模' },
    ],
    subCategories: [
      {
        id: 'modeling',
        title: '建模作品',
        images: [
          { src: '/image/works/3d/mode/001.webp' },
          { src: '/image/works/3d/mode/002.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/003.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/004.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/005.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/006.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/007.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/008.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/010.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/011.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/012.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/013.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/014.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/015.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/016.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/017.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/018.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/019.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/020.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/021.webp', alt: '角色建模' },
          { src: '/image/works/3d/mode/022.webp', alt: '角色建模' },
        ],
      },
      {
        id: 'texturing',
        title: '材质贴图',
        images: [
          { src: '/image/works/3d/caizhi/001.webp', alt: '材质贴图' },
          { src: '/image/works/3d/caizhi/002.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/003.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/004.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/005.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/006.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/007.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/008.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/009.webp', alt: 'PBR材质' },
          { src: '/image/works/3d/caizhi/010.webp', alt: 'PBR材质' },
        ],
      },
      {
        id: 'lighting',
        title: '灯光渲染',
        images: [
          { src: '/image/works/3d/xuanran/001.webp', alt: '灯光渲染' },
          { src: '/image/works/3d/xuanran/002.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/003.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/004.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/005.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/006.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/007.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/008.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/009.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/010.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/011.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/012.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/013.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/014.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/015.webp', alt: '场景渲染' },
          { src: '/image/works/3d/xuanran/016.webp', alt: '场景渲染' },
        ],
      },
      {
        id: 'animation',
        title: '三维动画',
        images: [
          { src: '/videos/001.mp4', alt: '三维动画', type: 'video' },
          { src: '/videos/002.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/003.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/004.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/005.mp4', alt: '动态效果', type: 'video' },
          { src: 'bilibili:BV1ZzB2BdE9R', alt: '三维动画作品', type: 'bilibili' },
          { src: '/videos/007.mp4', alt: '动态效果', type: 'video' },
          { src: 'bilibili:BV1BBB2B4EoL', alt: '三维动画作品', type: 'bilibili' },
          { src: '/videos/009.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/010.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/011.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/012.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/013.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/014.mp4', alt: '动态效果', type: 'video' },
          { src: '/videos/015.mp4', alt: '动态效果', type: 'video' },
        ],
      },
    ],
  },
  {
    id: 'graphic-design',
    title: '平面设计',
    icon: <Palette className="w-8 h-8" />,
    description: '品牌视觉、海报设计与排版。将创意转化为引人注目的视觉传达，提升品牌价值与识别度。',
    tools: ['Illustrator', 'InDesign', 'Photoshop', 'Canva'],
    images: [
      { src: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', alt: '品牌设计' },
      { src: '/image/works/pinmian/001.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/002.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/003.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/004.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/005.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/006.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/007.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/008.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/009.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/010.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/011.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/012.webp', alt: '品牌设计' },
      { src: '/image/works/pinmian/013.webp', alt: '品牌设计' },
    ],
  },
];
